num1=int(input('Ingrese dos numeros que no sean 0: '))
num2=int(input())
suma=int(num1 + num2)
div=float(num1 / num2)
mult=int(num1 * num2)
rest=int(num1 - num1)
print('El resultado de sumarlos entre si da: '+ str(suma))
print('El resultado de dividirlos entre si da: '+ str(div))
print('El resultado de multiplicarlos entre si da: '+ str(mult))
print('El resultado de restarlos entre si da: '+ str(rest))