num=int(input('Ingrese su numero para ver su tabla de multiplicar del 1 al 9: '))
print('La lista quedaria de la siguiente forma: ')
por1=int(num*1)
por2=int(num*2)
por3=int(num*3)
por4=int(num*4)
por5=int(num*5)
por6=int(num*6)
por7=int(num*7)
por8=int(num*8)
por9=int(num*9)
print(por1)
print(por2)
print(por3)
print(por4)
print(por5)
print(por6)
print(por7)
print(por8)
print(por9)

